# lang.py
translations = {
    "en": {
        "project_name": "Astro Notebook 2025",
        "app_description": "Log and explore your personal space odyssey (againeureka@gmail.com).",
        "tab_log": "Observation Log",
        "tab_data": "Data Management & Visualization",
        "sidebar_header": "Add a New Observation",
        "current_time": "Current Time",
        "search_label": "Enter celestial object name or ID",
        "search_placeholder": "Andromeda Galaxy, M31, Sirius",
        "celestial_id": "Celestial ID",
        "celestial_name_kr": "Korean Name",
        "ra_label": "Right Ascension (RA)",
        "dec_label": "Declination (Dec)",
        "notes_label": "Notes & Feelings",
        "notes_placeholder": "The sky was clear tonight, so I observed the Andromeda Galaxy with my binoculars.",
        "upload_file": "Upload a photo or sketch",
        "save_record": "Save Record",
        "success_save": "✅ Observation record successfully saved!",
        "error_search": "❌ Please search for a valid celestial object first.",
        "log_header": "My Observation Log",
        "select_date": "Select Date",
        "today": "Today",
        "no_records": "No observation records found for this date. Try adding a new one!",
        "editing_record": "Editing Record",
        "save_changes": "Save Changes",
        "cancel": "Cancel",
        "delete": "Delete",
        "edit": "Edit",
        "success_delete": "✅ Record successfully deleted.",
        "success_update": "✅ Record successfully updated.",
        "image_caption": "Current Photo",
        "new_notes": "Enter new notes",
        "new_image": "Upload a new photo",
        "file_not_found": "The image does not exist at the specified path.",
        "export_data_header": "Export Data",
        "export_json": "Export as JSON",
        "export_csv": "Export as CSV",
        "export_html": "Export as HTML",
        "export_db": "Export Database File (.db)",
        "map_header": "My Star Map of Observations",
        "map_title": "Celestial Positions by Observation Count",
        "no_map_data": "No observation records to display on the map.",
        "page": "Page",
        "previous": "Previous Page",
        "next": "Next Page",
        "language_selector": "Select Language"
    },
    "ko": {
        "project_name": "우주 수첩 2025",
        "app_description": "나만의 우주 항해 일지를 기록하고 탐험하세요 (againeureka@gmail.com).",
        "tab_log": "관측 일지",
        "tab_data": "데이터 관리 및 시각화",
        "sidebar_header": "새로운 관측 기록 추가",
        "current_time": "현재 시각",
        "search_label": "천체 이름 또는 ID를 입력하세요",
        "search_placeholder": "안드로메다 은하, M31, 시리우스",
        "celestial_id": "천체 ID",
        "celestial_name_kr": "한글 이름",
        "ra_label": "적경 (RA)",
        "dec_label": "적위 (Dec)",
        "notes_label": "관측 느낌 및 메모",
        "notes_placeholder": "오늘 밤 하늘이 맑아 안드로메다 은하를 쌍안경으로 관측했어요.",
        "upload_file": "사진 또는 스케치 업로드",
        "save_record": "기록 저장",
        "success_save": "✅ 관측 기록이 성공적으로 저장되었습니다!",
        "error_search": "❌ 유효한 천체 이름을 먼저 검색하세요.",
        "log_header": "나의 관측 일지",
        "select_date": "날짜 선택",
        "today": "오늘",
        "no_records": "해당 날짜에 관측 기록이 없습니다. 새로운 기록을 추가해보세요.",
        "editing_record": "기록 편집 중",
        "save_changes": "수정 완료",
        "cancel": "취소",
        "delete": "삭제",
        "edit": "편집",
        "success_delete": "✅ 기록이 성공적으로 삭제되었습니다.",
        "success_update": "✅ 기록이 성공적으로 업데이트되었습니다.",
        "image_caption": "현재 사진",
        "new_notes": "새로운 메모를 입력하세요",
        "new_image": "새로운 사진 업로드",
        "file_not_found": "경로에 이미지가 존재하지 않습니다.",
        "export_data_header": "데이터 내보내기",
        "export_json": "JSON 파일로 내보내기",
        "export_csv": "CSV 파일로 내보내기",
        "export_html": "HTML 파일로 내보내기",
        "export_db": "데이터베이스 파일(.db) 내보내기",
        "map_header": "나의 관측 우주 지도",
        "map_title": "관측 횟수별 천체 위치",
        "no_map_data": "지도에 표시할 관측 기록이 없습니다.",
        "page": "페이지",
        "previous": "이전 페이지",
        "next": "다음 페이지",
        "language_selector": "언어 선택"
    }
}